wx:
  token: abcd
  APPID: wx24308b9b27d0c3d8
  APPSECRET: 3160809c2e634dc2b1f28623c22bff36

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gzh?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
